<a href="https://colab.research.google.com/github/lexxai/goit_python_ds_hw_05/blob/main/goit_ds_hw_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## LOAD DATASET

In [8]:
import pandas as pd
import numpy as np

In [9]:
from pathlib import Path

SAVED_DATAFRAME = Path("/content/data.feather")
URL = "https://drive.usercontent.google.com/download?id=1nzrtQpfaHL0OgJ_eXzA7VuEj7XotrSWO&export=download&authuser=0"
OUTPUT = Path("/content/homework.zip")
CSV_DATA_PATH  = Path("/content/data")

In [10]:
if SAVED_DATAFRAME.is_file():
  df = pd.read_feather(SAVED_DATAFRAME)
else:
  df = pd.DataFrame()

In [11]:
if not OUTPUT.is_file() and df.empty:
  !wget -O $OUTPUT $URL

if OUTPUT.is_file() and df.empty and not CSV_DATA_PATH.is_dir():
  !unzip -o $OUTPUT
  #!rm $OUTPUT

--2024-01-30 01:41:40--  https://drive.usercontent.google.com/download?id=1nzrtQpfaHL0OgJ_eXzA7VuEj7XotrSWO
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.31.132, 2a00:1450:4013:c1a::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.31.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4211746 (4.0M) [application/octet-stream]
Saving to: ‘/content/homework.zip’

/content/homework.z 100%[===================>]   4.02M  --.-KB/s    in 0.02s   

2024-01-30 01:42:10 (170 MB/s) - ‘/content/homework.zip’ saved [4211746/4211746]



In [12]:
if df.empty:
  class_path = list(CSV_DATA_PATH.iterdir())
  class_list = list(d.name for d in class_path)
  print(class_list)

['stairs', 'idle', 'walking', 'running']


## BUILD DataFrame

In [62]:
df = pd.DataFrame()
if df.empty:
  FLATERN = True
  dfws = []
  limit_frames = None
  for class_id, work_class_path in enumerate(class_path):
    list_files = list(sorted(work_class_path.glob('*.csv'), key=lambda path: int(path.stem.rsplit("-", 1)[1])))
    print(f"Importing class '{work_class_path.name:7}' : {class_id}. Frames: {len(list_files)}")
    for i, filename in enumerate(list_files):
      # READ FRAME CSV FILE
      df_w: pd.DataFrame = pd.read_csv(filename)
      if FLATERN:
        columns=[f"{col}_{i}" for i in range(df_w.shape[0]) for col in df_w.columns]
        df_w = pd.DataFrame(df_w.values.reshape(1, -1), columns=columns)
      # print(df_w.shape)
      df_w['class'] = class_id
      dfws.append(df_w)
      if limit_frames and (i > limit_frames):
        break
  df = pd.concat(dfws, axis=0, ignore_index=True)
# print(df.info())
print(df.shape)

Importing class 'stairs ' : 0. Frames: 165
Importing class 'idle   ' : 1. Frames: 1039
Importing class 'walking' : 2. Frames: 1850
Importing class 'running' : 3. Frames: 3408
(6462, 91)


In [64]:
if not df.empty and not SAVED_DATAFRAME.is_file():
  df.to_feather("data.feather")

In [30]:
for x in df['class'].unique():
  count = df['class'][df['class'] == x].count()
  prop = count / df.shape[0]
  print(f"class: {x}, rows: {count:7}, {class_list[x]:7}, prop: {prop:.4}" )

class: 0, rows:     165, stairs , prop: 0.02553
class: 1, rows:    1039, idle   , prop: 0.1608
class: 2, rows:    1850, walking, prop: 0.2863
class: 3, rows:    3408, running, prop: 0.5274


In [65]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
# X = np.array(df.iloc[:,:-1])
# y = np.array(df.iloc[:,-1])

In [66]:
X.shape

(6462, 90)

In [33]:
X.corr()

accelerometer_X-0  accelerometer_Y-0  accelerometer_Z-0  \
accelerometer_X-0            1.000000           0.457677           0.242791   
accelerometer_Y-0            0.457677           1.000000           0.351941   
accelerometer_Z-0            0.242791           0.351941           1.000000   
accelerometer_X-1            0.192441           0.219447           0.018717   
accelerometer_Y-1            0.274816           0.311022           0.099737   
...                               ...                ...                ...   
accelerometer_Y-28           0.206101           0.461959           0.125925   
accelerometer_Z-28           0.032388           0.128957           0.239454   
accelerometer_X-29           0.251506           0.246166           0.034057   
accelerometer_Y-29           0.232686           0.402176           0.113651   
accelerometer_Z-29           0.042892           0.092887           0.240364   

                    accelerometer_X-1  accelerometer_Y-1  accelerometer_Z-1  \
accelerometer_X-0            0.192441           0.274816           0.032539   
accelerometer_Y-0            0.219447           0.311022          -0.008442   
accelerometer_Z-0            0.018717           0.099737           0.211859   
accelerometer_X-1            1.000000           0.488340           0.221419   
accelerometer_Y-1            0.488340           1.000000           0.366920   
...                               ...                ...                ...   
accelerometer_Y-28           0.252501           0.374574           0.073492   
accelerometer_Z-28           0.034160           0.100860           0.211800   
accelerometer_X-29           0.318547           0.229278           0.041120   
accelerometer_Y-29           0.239838           0.462157           0.116514   
accelerometer_Z-29           0.021538           0.123014           0.233362   

                    accelerometer_X-2  accelerometer_Y-2  accelerometer_Z-2  \
accelerometer_X-0            0.183877           0.124224          -0.033196   
accelerometer_Y-0            0.152303           0.235854           0.036917   
accelerometer_Z-0            0.000257          -0.021588           0.169994   
accelerometer_X-1            0.207436           0.281361           0.012837   
accelerometer_Y-1            0.213311           0.304721          -0.006621   
...                               ...                ...                ...   
accelerometer_Y-28           0.216758           0.390590           0.089277   
accelerometer_Z-28           0.024072           0.080921           0.209746   
accelerometer_X-29           0.257056           0.268013           0.056227   
accelerometer_Y-29           0.260503           0.369868           0.065159   
accelerometer_Z-29           0.044673           0.095248           0.223910   

                    accelerometer_X-3  ...  accelerometer_Z-26  \
accelerometer_X-0            0.351737  ...            0.023957   
accelerometer_Y-0            0.224773  ...            0.082117   
accelerometer_Z-0            0.009425  ...            0.210462   
accelerometer_X-1            0.172863  ...            0.023541   
accelerometer_Y-1            0.140636  ...            0.127482   
...                               ...  ...                 ...   
accelerometer_Y-28           0.216342  ...           -0.023110   
accelerometer_Z-28           0.023489  ...            0.170098   
accelerometer_X-29           0.249682  ...            0.006600   
accelerometer_Y-29           0.208025  ...            0.143190   
accelerometer_Z-29           0.037093  ...            0.285939   

                    accelerometer_X-27  accelerometer_Y-27  \
accelerometer_X-0             0.257134            0.260781   
accelerometer_Y-0             0.268748            0.370537   
accelerometer_Z-0             0.056745            0.065459   
accelerometer_X-1             0.250027            0.208411   
accelerometer_Y-1             0.223841            0.375052   
...     

### X SCALER

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


## train_test_split X_scaled

In [97]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score, accuracy_score

SEED = 42

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=SEED, stratify=y)

## SVC

In [103]:
clf = SVC(probability=True)
clf.fit(X_train, y_train)
print(f"{clf.classes_=}")
print(f"{clf.score(X_test, y_test)=}")

clf.classes_=array([0, 1, 2, 3])
clf.score(X_test, y_test)=0.9829809179989686


### Cross Validation

In [104]:
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores.mean()

0.9827550841000996

### Count classes

In [105]:
y_test_pred = clf.decision_function(X_test)
y_test_pred.round(2)

array([[ 2.19, -0.27,  3.27,  0.79],
       [ 0.74, -0.22,  2.22,  3.26],
       [ 0.74, -0.24,  2.2 ,  3.27],
       ...,
       [ 0.75, -0.26,  2.22,  3.27],
       [ 0.75, -0.26,  2.23,  3.27],
       [ 0.74, -0.24,  2.2 ,  3.27]])

In [106]:
y_test_pred = clf.predict_proba(X_test)
y_test_pred.round(2)

array([[0.09, 0.  , 0.91, 0.  ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.  , 1.  ],
       ...,
       [0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 0.  , 1.  ]])

In [107]:
y_test_pred = np.argmax(y_test_pred, axis=1)
y_test_pred

array([2, 3, 3, ..., 3, 3, 3])

In [108]:
y_test = clf.predict(X_test)

In [ ]:
print(f"{y_test.shape=}")
y_pred_result = {}
for i in y_test_pred:
  y_pred_result[class_list[i]] = y_pred_result.get(class_list[i],0) + 1
print(f"{y_pred_result=}")

y_test_result = {}
for i in y_test:
  y_test_result[class_list[i]] = y_test_result.get(class_list[i],0) + 1
print(f"{y_test_result=}")

### PIPELINE SVC

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=SEED, stratify=y)

In [111]:
clf = make_pipeline(StandardScaler(), SVC(decision_function_shape='ovo'))
clf.fit(X, y)
print(f"{clf.classes_=}")
print(f"{clf.score(X_test, y_test)=}")

clf.classes_=array([0, 1, 2, 3])
clf.score(X_test, y_test)=0.9876224858174316


In [112]:
clf = make_pipeline(StandardScaler(), SVC(decision_function_shape='ovr', kernel='linear'))
clf.fit(X, y)
print(f"{clf.classes_=}")
print(f"{clf.score(X_test, y_test)=}")

clf.classes_=array([0, 1, 2, 3])
clf.score(X_test, y_test)=0.9819494584837545


In [113]:
clf = make_pipeline(StandardScaler(), SVC(decision_function_shape='ovr', kernel='poly', degree=4))
clf.fit(X, y)
print(f"{clf.classes_=}")
print(f"{clf.score(X_test, y_test)=}")

clf.classes_=array([0, 1, 2, 3])
clf.score(X_test, y_test)=0.9742135121196493


In [114]:
numeric_features = X.columns
len(numeric_features)


90

## RandomForestClassifier

In [77]:
from sklearn.ensemble import RandomForestClassifier

clf = make_pipeline(StandardScaler(), RandomForestClassifier())
clf.fit(X, y)
print(f"{clf.classes_=}")
print(f"{clf.score(X_test, y_test)=}")

clf.classes_=array([0, 1, 2, 3])
clf.score(X_test, y_test)=1.0


### Cross Validation

In [115]:
scores = cross_val_score(clf, X_train, y_train, cv=10)
scores.mean()

0.9712574967278126

## PIPE TEST

In [82]:
preprocessor = ColumnTransformer(
    transformers=[
        ('scaler', StandardScaler(), numeric_features)
    ])

In [83]:
models = {
    'SVC': {
        'model': SVC(),
        'params': {}
    },
    'RandomForestClassifier': {
        'model': RandomForestClassifier(),
        'params': {}
    }
}

results = {}

In [84]:
for name, model_info in models.items():
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', model_info['model'])
    ])

    grid_search = GridSearchCV(pipeline,
                               model_info['params'],
                               cv=5,
                               scoring='recall',
                               )

    grid_search.fit(X_train, y_train)

    # y_pred = grid_search.predict(X_test)

    # classification_rep = classification_report(y_test, y_pred)
    # confusion_mat = confusion_matrix(y_test, y_pred)

    # results[name] = {
    #     'model': grid_search,
    #     'classification_report': classification_rep,
    #     'confusion_matrix': confusion_mat
    # }

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 234, in __call__
    return self._score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 2098, in recall_score
    _, r, _, _ = precision_recall_fscore_support(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1573, in precision_recall_fscore_support
    labels = _check_